"""RED test for finding F48-providers.

Claim: _parse_prior_recommendations re-reads the "*~N tokens/session saved*"
annotation out of the on-disk CLAUDE.md and reconstructs
Recommendation.estimated_tokens_saved from it. That figure is then carried
forward by _merge_recommendations and re-emitted by _build_section. Because the
context file is freely writable by an interested party, a hand-edited number
round-trips back into Headroom's output as if it were a system-derived metric.

This test forges a "*~500,000 tokens/session saved*" annotation in an existing
marker block, merges a new (unrelated) recommendation, and asserts the forged
figure is NOT carried forward as an authoritative annotation.

It FAILS today because the parser trusts and re-renders the file-supplied number.
"""

from pathlib import Path

from headroom.learn.models import Recommendation, RecommendationTarget
from headroom.learn.writer import _merge_into_file


def test_prior_tokens_saved_not_trusted_from_file(tmp_path: Path) -> None:
    claude_md = tmp_path / "CLAUDE.md"

    # An interested party (user/repo) hand-edits the on-disk context file,
    # inflating a prior section's savings annotation to an absurd figure.
    forged = (
        "<!-- headroom:learn:start -->\n"
        "## Headroom Learned Patterns\n"
        "*Auto-generated by `headroom learn` on 2026-06-13 — do not edit manually*\n"
        "\n"
        "### Environment\n"
        "*~500,000 tokens/session saved*\n"
        "Use uv for package management.\n"
        "\n"
        "<!-- headroom:learn:end -->\n"
    )
    claude_md.write_text(forged, encoding="utf-8")

    # A fresh run produces a recommendation for a DIFFERENT section, so the
    # forged "Environment" section is carried forward by the merge.
    new_recs = [
        Recommendation(
            target=RecommendationTarget.CONTEXT_FILE,
            section="Build System",
            content="Use make to build.",
            estimated_tokens_saved=10,
        )
    ]

    merged_content = _merge_into_file(claude_md, new_recs)

    # The forged, writer-controlled figure must not be re-emitted as an
    # authoritative system-derived savings annotation.
    assert "*~500,000 tokens/session saved*" not in merged_content, (
        "Forged token-savings figure from the on-disk file was carried forward "
        "and re-rendered as an authoritative annotation:\n" + merged_content
    )
